// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SendSmSProto.proto

package SendSms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// thay giai thich ki hon cai AuthMessage hoat dong ntn? server lam gi voi no?
type AuthMessage struct {
	// appID chua gi? de lam gi?
	AppID     string `protobuf:"bytes,1,opt,name=appID" json:"appID,omitempty"`
	TimeStamp string `protobuf:"bytes,2,opt,name=timeStamp" json:"timeStamp,omitempty"`
	// authSignature chua gi? de lam gi?
	AuthSignature        string   `protobuf:"bytes,3,opt,name=authSignature" json:"authSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMessage) Reset()         { *m = AuthMessage{} }
func (m *AuthMessage) String() string { return proto.CompactTextString(m) }
func (*AuthMessage) ProtoMessage()    {}
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_SendSmSProto_3deb8635d1649dd2, []int{0}
}
func (m *AuthMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMessage.Unmarshal(m, b)
}
func (m *AuthMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMessage.Marshal(b, m, deterministic)
}
func (dst *AuthMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMessage.Merge(dst, src)
}
func (m *AuthMessage) XXX_Size() int {
	return xxx_messageInfo_AuthMessage.Size(m)
}
func (m *AuthMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMessage proto.InternalMessageInfo

func (m *AuthMessage) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *AuthMessage) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *AuthMessage) GetAuthSignature() string {
	if m != nil {
		return m.AuthSignature
	}
	return ""
}

type SmsAgentInfo struct {
	// /fullnumber là number của thằng nào thế ạ?
	FullNumber string `protobuf:"bytes,1,opt,name=fullNumber" json:"fullNumber,omitempty"`
	// dailyLimit là số lượng tin nhắn trong 1 ngày phải không thầy?
	DailyLimit int32 `protobuf:"varint,2,opt,name=dailyLimit" json:"dailyLimit,omitempty"`
	// totalLimit giới hạn số lượng trong bao lâu thế ạ?
	TotalLimit           int32    `protobuf:"varint,3,opt,name=totalLimit" json:"totalLimit,omitempty"`
	RewardAddress        string   `protobuf:"bytes,4,opt,name=rewardAddress" json:"rewardAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsAgentInfo) Reset()         { *m = SmsAgentInfo{} }
func (m *SmsAgentInfo) String() string { return proto.CompactTextString(m) }
func (*SmsAgentInfo) ProtoMessage()    {}
func (*SmsAgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_SendSmSProto_3deb8635d1649dd2, []int{1}
}
func (m *SmsAgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsAgentInfo.Unmarshal(m, b)
}
func (m *SmsAgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsAgentInfo.Marshal(b, m, deterministic)
}
func (dst *SmsAgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsAgentInfo.Merge(dst, src)
}
func (m *SmsAgentInfo) XXX_Size() int {
	return xxx_messageInfo_SmsAgentInfo.Size(m)
}
func (m *SmsAgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsAgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SmsAgentInfo proto.InternalMessageInfo

func (m *SmsAgentInfo) GetFullNumber() string {
	if m != nil {
		return m.FullNumber
	}
	return ""
}

func (m *SmsAgentInfo) GetDailyLimit() int32 {
	if m != nil {
		return m.DailyLimit
	}
	return 0
}

func (m *SmsAgentInfo) GetTotalLimit() int32 {
	if m != nil {
		return m.TotalLimit
	}
	return 0
}

func (m *SmsAgentInfo) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

// Khi client (android) nhận được SMS thì có thể forward lên server qua tin nhắn này
type IncomingMsg struct {
	// fromNumber co phai la sdt cua app khong?
	FromNumber           string   `protobuf:"bytes,1,opt,name=fromNumber" json:"fromNumber,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	TimeStamp            int64    `protobuf:"varint,3,opt,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncomingMsg) Reset()         { *m = IncomingMsg{} }
func (m *IncomingMsg) String() string { return proto.CompactTextString(m) }
func (*IncomingMsg) ProtoMessage()    {}
func (*IncomingMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_SendSmSProto_3deb8635d1649dd2, []int{2}
}
func (m *IncomingMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncomingMsg.Unmarshal(m, b)
}
func (m *IncomingMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncomingMsg.Marshal(b, m, deterministic)
}
func (dst *IncomingMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncomingMsg.Merge(dst, src)
}
func (m *IncomingMsg) XXX_Size() int {
	return xxx_messageInfo_IncomingMsg.Size(m)
}
func (m *IncomingMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_IncomingMsg.DiscardUnknown(m)
}

var xxx_messageInfo_IncomingMsg proto.InternalMessageInfo

func (m *IncomingMsg) GetFromNumber() string {
	if m != nil {
		return m.FromNumber
	}
	return ""
}

func (m *IncomingMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *IncomingMsg) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type C2SMessage struct {
	// Types that are valid to be assigned to AuthClient:
	//	*C2SMessage_Auth
	//	*C2SMessage_SmsAgent
	AuthClient      isC2SMessage_AuthClient `protobuf_oneof:"authClient"`
	TimeStamp       int64                   `protobuf:"varint,3,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Success         bool                    `protobuf:"varint,6,opt,name=success" json:"success,omitempty"`
	IncomingMessage *IncomingMsg            `protobuf:"bytes,4,opt,name=incomingMessage" json:"incomingMessage,omitempty"`
	// extData de lam gi?
	ExtData              string   `protobuf:"bytes,5,opt,name=extData" json:"extData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SMessage) Reset()         { *m = C2SMessage{} }
func (m *C2SMessage) String() string { return proto.CompactTextString(m) }
func (*C2SMessage) ProtoMessage()    {}
func (*C2SMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_SendSmSProto_3deb8635d1649dd2, []int{3}
}
func (m *C2SMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SMessage.Unmarshal(m, b)
}
func (m *C2SMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SMessage.Marshal(b, m, deterministic)
}
func (dst *C2SMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SMessage.Merge(dst, src)
}
func (m *C2SMessage) XXX_Size() int {
	return xxx_messageInfo_C2SMessage.Size(m)
}
func (m *C2SMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SMessage.DiscardUnknown(m)
}

var xxx_messageInfo_C2SMessage proto.InternalMessageInfo

type isC2SMessage_AuthClient interface {
	isC2SMessage_AuthClient()
}

type C2SMessage_Auth struct {
	Auth *AuthMessage `protobuf:"bytes,1,opt,name=auth,oneof"`
}
type C2SMessage_SmsAgent struct {
	SmsAgent *SmsAgentInfo `protobuf:"bytes,2,opt,name=smsAgent,oneof"`
}

func (*C2SMessage_Auth) isC2SMessage_AuthClient()     {}
func (*C2SMessage_SmsAgent) isC2SMessage_AuthClient() {}

func (m *C2SMessage) GetAuthClient() isC2SMessage_AuthClient {
	if m != nil {
		return m.AuthClient
	}
	return nil
}

func (m *C2SMessage) GetAuth() *AuthMessage {
	if x, ok := m.GetAuthClient().(*C2SMessage_Auth); ok {
		return x.Auth
	}
	return nil
}

func (m *C2SMessage) GetSmsAgent() *SmsAgentInfo {
	if x, ok := m.GetAuthClient().(*C2SMessage_SmsAgent); ok {
		return x.SmsAgent
	}
	return nil
}

func (m *C2SMessage) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *C2SMessage) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *C2SMessage) GetIncomingMessage() *IncomingMsg {
	if m != nil {
		return m.IncomingMessage
	}
	return nil
}

func (m *C2SMessage) GetExtData() string {
	if m != nil {
		return m.ExtData
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*C2SMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _C2SMessage_OneofMarshaler, _C2SMessage_OneofUnmarshaler, _C2SMessage_OneofSizer, []interface{}{
		(*C2SMessage_Auth)(nil),
		(*C2SMessage_SmsAgent)(nil),
	}
}

func _C2SMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*C2SMessage)
	// authClient
	switch x := m.AuthClient.(type) {
	case *C2SMessage_Auth:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Auth); err != nil {
			return err
		}
	case *C2SMessage_SmsAgent:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SmsAgent); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("C2SMessage.AuthClient has unexpected type %T", x)
	}
	return nil
}

func _C2SMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*C2SMessage)
	switch tag {
	case 1: // authClient.auth
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthMessage)
		err := b.DecodeMessage(msg)
		m.AuthClient = &C2SMessage_Auth{msg}
		return true, err
	case 2: // authClient.smsAgent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SmsAgentInfo)
		err := b.DecodeMessage(msg)
		m.AuthClient = &C2SMessage_SmsAgent{msg}
		return true, err
	default:
		return false, nil
	}
}

func _C2SMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*C2SMessage)
	// authClient
	switch x := m.AuthClient.(type) {
	case *C2SMessage_Auth:
		s := proto.Size(x.Auth)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *C2SMessage_SmsAgent:
		s := proto.Size(x.SmsAgent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// message from server to client
// thuc thien cac lệnh khac nhau
// lệnh SendSms
type CommandSendSmS struct {
	ToNumber             string   `protobuf:"bytes,1,opt,name=toNumber" json:"toNumber,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandSendSmS) Reset()         { *m = CommandSendSmS{} }
func (m *CommandSendSmS) String() string { return proto.CompactTextString(m) }
func (*CommandSendSmS) ProtoMessage()    {}
func (*CommandSendSmS) Descriptor() ([]byte, []int) {
	return fileDescriptor_SendSmSProto_3deb8635d1649dd2, []int{4}
}
func (m *CommandSendSmS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSendSmS.Unmarshal(m, b)
}
func (m *CommandSendSmS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSendSmS.Marshal(b, m, deterministic)
}
func (dst *CommandSendSmS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSendSmS.Merge(dst, src)
}
func (m *CommandSendSmS) XXX_Size() int {
	return xxx_messageInfo_CommandSendSmS.Size(m)
}
func (m *CommandSendSmS) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSendSmS.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSendSmS proto.InternalMessageInfo

func (m *CommandSendSmS) GetToNumber() string {
	if m != nil {
		return m.ToNumber
	}
	return ""
}

func (m *CommandSendSmS) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type S2CMesssage struct {
	// Types that are valid to be assigned to ChoseCommand:
	//	*S2CMesssage_Message
	ChoseCommand         isS2CMesssage_ChoseCommand `protobuf_oneof:"choseCommand"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *S2CMesssage) Reset()         { *m = S2CMesssage{} }
func (m *S2CMesssage) String() string { return proto.CompactTextString(m) }
func (*S2CMesssage) ProtoMessage()    {}
func (*S2CMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor_SendSmSProto_3deb8635d1649dd2, []int{5}
}
func (m *S2CMesssage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CMesssage.Unmarshal(m, b)
}
func (m *S2CMesssage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CMesssage.Marshal(b, m, deterministic)
}
func (dst *S2CMesssage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CMesssage.Merge(dst, src)
}
func (m *S2CMesssage) XXX_Size() int {
	return xxx_messageInfo_S2CMesssage.Size(m)
}
func (m *S2CMesssage) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CMesssage.DiscardUnknown(m)
}

var xxx_messageInfo_S2CMesssage proto.InternalMessageInfo

type isS2CMesssage_ChoseCommand interface {
	isS2CMesssage_ChoseCommand()
}

type S2CMesssage_Message struct {
	Message *CommandSendSmS `protobuf:"bytes,1,opt,name=Message,oneof"`
}

func (*S2CMesssage_Message) isS2CMesssage_ChoseCommand() {}

func (m *S2CMesssage) GetChoseCommand() isS2CMesssage_ChoseCommand {
	if m != nil {
		return m.ChoseCommand
	}
	return nil
}

func (m *S2CMesssage) GetMessage() *CommandSendSmS {
	if x, ok := m.GetChoseCommand().(*S2CMesssage_Message); ok {
		return x.Message
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*S2CMesssage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _S2CMesssage_OneofMarshaler, _S2CMesssage_OneofUnmarshaler, _S2CMesssage_OneofSizer, []interface{}{
		(*S2CMesssage_Message)(nil),
	}
}

func _S2CMesssage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*S2CMesssage)
	// choseCommand
	switch x := m.ChoseCommand.(type) {
	case *S2CMesssage_Message:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Message); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("S2CMesssage.ChoseCommand has unexpected type %T", x)
	}
	return nil
}

func _S2CMesssage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*S2CMesssage)
	switch tag {
	case 1: // choseCommand.Message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CommandSendSmS)
		err := b.DecodeMessage(msg)
		m.ChoseCommand = &S2CMesssage_Message{msg}
		return true, err
	default:
		return false, nil
	}
}

func _S2CMesssage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*S2CMesssage)
	// choseCommand
	switch x := m.ChoseCommand.(type) {
	case *S2CMesssage_Message:
		s := proto.Size(x.Message)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*AuthMessage)(nil), "SendSms.AuthMessage")
	proto.RegisterType((*SmsAgentInfo)(nil), "SendSms.SmsAgentInfo")
	proto.RegisterType((*IncomingMsg)(nil), "SendSms.IncomingMsg")
	proto.RegisterType((*C2SMessage)(nil), "SendSms.C2SMessage")
	proto.RegisterType((*CommandSendSmS)(nil), "SendSms.CommandSendSmS")
	proto.RegisterType((*S2CMesssage)(nil), "SendSms.S2CMesssage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SMSBlockChainHub service

type SMSBlockChainHubClient interface {
	BiDiMessage(ctx context.Context, opts ...grpc.CallOption) (SMSBlockChainHub_BiDiMessageClient, error)
}

type sMSBlockChainHubClient struct {
	cc *grpc.ClientConn
}

func NewSMSBlockChainHubClient(cc *grpc.ClientConn) SMSBlockChainHubClient {
	return &sMSBlockChainHubClient{cc}
}

func (c *sMSBlockChainHubClient) BiDiMessage(ctx context.Context, opts ...grpc.CallOption) (SMSBlockChainHub_BiDiMessageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SMSBlockChainHub_serviceDesc.Streams[0], c.cc, "/SendSms.SMSBlockChainHub/BiDiMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &sMSBlockChainHubBiDiMessageClient{stream}
	return x, nil
}

type SMSBlockChainHub_BiDiMessageClient interface {
	Send(*C2SMessage) error
	Recv() (*S2CMesssage, error)
	grpc.ClientStream
}

type sMSBlockChainHubBiDiMessageClient struct {
	grpc.ClientStream
}

func (x *sMSBlockChainHubBiDiMessageClient) Send(m *C2SMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sMSBlockChainHubBiDiMessageClient) Recv() (*S2CMesssage, error) {
	m := new(S2CMesssage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SMSBlockChainHub service

type SMSBlockChainHubServer interface {
	BiDiMessage(SMSBlockChainHub_BiDiMessageServer) error
}

func RegisterSMSBlockChainHubServer(s *grpc.Server, srv SMSBlockChainHubServer) {
	s.RegisterService(&_SMSBlockChainHub_serviceDesc, srv)
}

func _SMSBlockChainHub_BiDiMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SMSBlockChainHubServer).BiDiMessage(&sMSBlockChainHubBiDiMessageServer{stream})
}

type SMSBlockChainHub_BiDiMessageServer interface {
	Send(*S2CMesssage) error
	Recv() (*C2SMessage, error)
	grpc.ServerStream
}

type sMSBlockChainHubBiDiMessageServer struct {
	grpc.ServerStream
}

func (x *sMSBlockChainHubBiDiMessageServer) Send(m *S2CMesssage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sMSBlockChainHubBiDiMessageServer) Recv() (*C2SMessage, error) {
	m := new(C2SMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SMSBlockChainHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SendSms.SMSBlockChainHub",
	HandlerType: (*SMSBlockChainHubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BiDiMessage",
			Handler:       _SMSBlockChainHub_BiDiMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "SendSmSProto.proto",
}

func init() { proto.RegisterFile("SendSmSProto.proto", fileDescriptor_SendSmSProto_3deb8635d1649dd2) }

var fileDescriptor_SendSmSProto_3deb8635d1649dd2 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xdf, 0x6a, 0xdb, 0x30,
	0x18, 0xc5, 0xe3, 0xa4, 0x69, 0xd2, 0xcf, 0x59, 0x3b, 0xb4, 0x8e, 0x99, 0x32, 0x46, 0x31, 0x1b,
	0x84, 0x5d, 0x84, 0x91, 0xdc, 0x17, 0xf2, 0x87, 0xe1, 0x40, 0x33, 0x8a, 0xc5, 0xd8, 0xb5, 0x62,
	0xab, 0x8e, 0x98, 0x25, 0x19, 0x49, 0x66, 0xdb, 0x43, 0xec, 0x6e, 0x4f, 0xb0, 0x27, 0x1d, 0x92,
	0xff, 0xc4, 0x29, 0xac, 0x37, 0x21, 0xdf, 0xf9, 0x0e, 0x3a, 0x47, 0x3f, 0x25, 0x80, 0x30, 0x15,
	0x29, 0xe6, 0xf8, 0x41, 0x49, 0x23, 0x67, 0x85, 0xfd, 0x44, 0xa3, 0x4a, 0xd3, 0x61, 0x06, 0xfe,
	0xb2, 0x34, 0x87, 0x1d, 0xd5, 0x9a, 0x64, 0x14, 0x5d, 0xc3, 0x90, 0x14, 0xc5, 0x76, 0x13, 0x78,
	0xb7, 0xde, 0xf4, 0x22, 0xae, 0x06, 0xf4, 0x16, 0x2e, 0x0c, 0xe3, 0x14, 0x1b, 0xc2, 0x8b, 0xa0,
	0xef, 0x36, 0x47, 0x01, 0xbd, 0x87, 0x17, 0xa4, 0x34, 0x07, 0xcc, 0x32, 0x41, 0x4c, 0xa9, 0x68,
	0x30, 0x70, 0x8e, 0x53, 0x31, 0xfc, 0xe3, 0xc1, 0x04, 0x73, 0xbd, 0xcc, 0xa8, 0x30, 0x5b, 0xf1,
	0x28, 0xd1, 0x3b, 0x80, 0xc7, 0x32, 0xcf, 0xbf, 0x94, 0x7c, 0x4f, 0x55, 0x9d, 0xd7, 0x51, 0xec,
	0x3e, 0x25, 0x2c, 0xff, 0x75, 0xcf, 0x38, 0x33, 0x2e, 0x75, 0x18, 0x77, 0x14, 0xbb, 0x37, 0xd2,
	0x90, 0xbc, 0xda, 0x0f, 0xaa, 0xfd, 0x51, 0xb1, 0xb5, 0x14, 0xfd, 0x41, 0x54, 0xba, 0x4c, 0x53,
	0x45, 0xb5, 0x0e, 0xce, 0xaa, 0x5a, 0x27, 0x62, 0x48, 0xc1, 0xdf, 0x8a, 0x44, 0x72, 0x26, 0xb2,
	0x9d, 0xce, 0x5c, 0x29, 0x25, 0xf9, 0x93, 0x52, 0xad, 0x82, 0x02, 0x18, 0x25, 0x52, 0x18, 0x2a,
	0x4c, 0xcd, 0xa1, 0x19, 0x4f, 0x19, 0xd9, 0x36, 0x83, 0x0e, 0xa3, 0xf0, 0x77, 0x1f, 0x60, 0x3d,
	0xc7, 0x0d, 0xe6, 0x8f, 0x70, 0x66, 0xe9, 0xb8, 0x00, 0x7f, 0x7e, 0x3d, 0xab, 0x5f, 0x63, 0xd6,
	0x79, 0x8a, 0xa8, 0x17, 0x3b, 0x0f, 0x5a, 0xc0, 0x58, 0xd7, 0xdc, 0x5c, 0xa6, 0x3f, 0x7f, 0xdd,
	0xfa, 0xbb, 0x40, 0xa3, 0x5e, 0xdc, 0x1a, 0x9f, 0x6f, 0x63, 0x6f, 0xa1, 0xcb, 0x24, 0xb1, 0x50,
	0xce, 0x6f, 0xbd, 0xe9, 0x38, 0x6e, 0x46, 0x74, 0x07, 0x57, 0xac, 0xc1, 0x51, 0xf5, 0x70, 0xd8,
	0xba, 0x1d, 0x3b, 0xb8, 0xe2, 0xa7, 0x66, 0x7b, 0x32, 0xfd, 0x69, 0x36, 0xc4, 0x90, 0x60, 0x58,
	0xf1, 0xa9, 0xc7, 0xd5, 0x04, 0xc0, 0x5e, 0x67, 0x9d, 0x33, 0x2a, 0x4c, 0xf8, 0x19, 0x2e, 0xd7,
	0x92, 0x73, 0x22, 0xd2, 0xfa, 0xc7, 0x89, 0x6e, 0x60, 0x6c, 0xe4, 0x09, 0xf7, 0x76, 0xfe, 0x3f,
	0xf5, 0x30, 0x06, 0x1f, 0xcf, 0xd7, 0x36, 0xdd, 0xc5, 0x2f, 0x60, 0xd4, 0xd4, 0xae, 0xd0, 0xbe,
	0x69, 0x6b, 0x9f, 0xc6, 0x45, 0xbd, 0xb8, 0x71, 0xae, 0x2e, 0x61, 0x92, 0x1c, 0xa4, 0xa6, 0xb5,
	0x63, 0x1e, 0xc3, 0x4b, 0xbc, 0xc3, 0xab, 0x5c, 0x26, 0xdf, 0xd7, 0x07, 0xc2, 0x44, 0x54, 0xee,
	0xd1, 0x1d, 0xf8, 0x2b, 0xb6, 0x61, 0xcd, 0x35, 0x5f, 0x1d, 0x8f, 0x6d, 0x1f, 0xf5, 0xe6, 0x88,
	0xa8, 0x53, 0x29, 0xec, 0x4d, 0xbd, 0x4f, 0xde, 0xea, 0x03, 0x5c, 0x31, 0x39, 0xcb, 0x54, 0x91,
	0xcc, 0xbe, 0x6a, 0xaa, 0xec, 0xf9, 0x60, 0xbf, 0x44, 0x34, 0x2f, 0xa8, 0x7a, 0xf0, 0xfe, 0xf6,
	0x07, 0xd1, 0xfd, 0xb7, 0xfd, 0xb9, 0xfb, 0x77, 0x2e, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x76,
	0x51, 0x10, 0x98, 0xb3, 0x03, 0x00, 0x00,
}
